version: 2

services:
  - type: web
    name: tilesgalleria-backend
    source: ./Backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromService:
          type: pserv
          name: tilesgalleria-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: APP_NAME
        value: TilesGalleriaAPI
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: riteshdhebe12345@gmail.com
      - key: SMTP_PASS
        value: your_app_password  # Replace with actual app password

  - type: web
    name: tilesgalleria-frontend
    source: ./tilesgalleria-dashboard
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: tilesgalleria-backend
          property: host

  - type: pserv
    name: tilesgalleria-db
    env: mongo
    region: oregon
    plan: starter